name = "BinaryBuilder"
uuid = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.5.6"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BinaryBuilderBase = "7f725544-6523-48cd-82d1-3fa08ff4056e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
ObjectFile = "d8793406-e978-5875-9003-1fc021f44a92"
OutputCollectors = "6c11c7d4-943b-4e2b-80de-f2cfc2930a8c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgLicenses = "fc669557-7ec9-5e45-bca9-462afbc28879"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Registrator = "4418983a-e44d-11e8-3aec-9789530b3b3e"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
ghr_jll = "07c12ed4-43bc-5495-8a2a-d5838ef8d533"

[compat]
ArgParse = "1.1"
BinaryBuilderBase = "1.20"
GitHub = "5.1"
HTTP = "0.8, 0.9, 1"
JLD2 = "0.1.6, 0.2, 0.3, 0.4"
JLLWrappers = "1.2.0"
JSON = "0.21"
LoggingExtras = "0.4, 1"
ObjectFile = "0.3.6"
OutputCollectors = "0.1"
PkgLicenses = "0.2"
Registrator = "1.1"
RegistryTools = "2.1"
Scratch = "1.0"
ghr_jll = "0.13, 0.14"
julia = "1.7"

[extras]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VT100 = "7774df62-37c0-5c21-b34d-f6d7f98f54bc"

[targets]
test = ["JLLWrappers", "Tar", "Test", "VT100"]
